// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6RjiDX3A4o6MWffdFpsUNfHg5qcEQ-8',
    appId: '1:143769500845:web:5503a8b621c9cb410d5a24',
    messagingSenderId: '143769500845',
    projectId: 'hotel-management-btl',
    authDomain: 'hotel-management-btl.firebaseapp.com',
    storageBucket: 'hotel-management-btl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbR0a2rSFDmR57gafl7ObVF920euFhW5M',
    appId: '1:143769500845:android:13e43c3fac07c89e0d5a24',
    messagingSenderId: '143769500845',
    projectId: 'hotel-management-btl',
    storageBucket: 'hotel-management-btl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJJWhBuSAbJcgsSKR9lbGoVaaCcp5me0',
    appId: '1:143769500845:ios:3587be68f7f1116c0d5a24',
    messagingSenderId: '143769500845',
    projectId: 'hotel-management-btl',
    storageBucket: 'hotel-management-btl.firebasestorage.app',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJJWhBuSAbJcgsSKR9lbGoVaaCcp5me0',
    appId: '1:143769500845:ios:3587be68f7f1116c0d5a24',
    messagingSenderId: '143769500845',
    projectId: 'hotel-management-btl',
    storageBucket: 'hotel-management-btl.firebasestorage.app',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd6RjiDX3A4o6MWffdFpsUNfHg5qcEQ-8',
    appId: '1:143769500845:web:e6f3f1b1daeef2690d5a24',
    messagingSenderId: '143769500845',
    projectId: 'hotel-management-btl',
    authDomain: 'hotel-management-btl.firebaseapp.com',
    storageBucket: 'hotel-management-btl.firebasestorage.app',
  );
}
